export const RULER_LEFT_PADDING = 5;

export const SIDEBAR_WIDTH = 296;

export const TIMELINE_LEFT_PADDING = RULER_LEFT_PADDING;
export const START_PAGE_X = SIDEBAR_WIDTH;

export const MIN_ZOOM_WIDTH_IN_PIXELS = 10;
